name: Auto-Release on PR Merge

on:
  pull_request:
  #   types: [closed]

jobs:
  release:
    # if: github.event.pull_request.merged == 'true'
    runs-on: ubuntu-latest
    container: dart:2.14.4

    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Release
        run: |
          echo ${{github.repository}}
          echo ${{github.event.pull_request.id}}
          echo ______
          export PATH="$PATH":"$HOME/.pub-cache/bin"
          export GITHUB_TOKEN=${{secrets.GITHUB_TOKEN}}
          