name: Release unreleased PR

# Runs when a PR merges. 
# See https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#running-your-workflow-when-a-pull-request-merges
on:
  pull_request:
    types:
      - closed

jobs:
  release:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Apply unreleased label
        uses: actions/github-script@v3
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            github.issues.addLabels({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              labels: ['unreleased']
            })
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 2
          ref: main
      - name: Release
        run: |
          git config --global user.name ${{ secrets.USER_NAME }}
          git config --global user.email ${{ secrets.USER_EMAIL }}
          export PATH="$PATH":"$HOME/.pub-cache/bin"
          export GITHUB_TOKEN=${{secrets.MACHINE_GITHUB_API_TOKEN}}
          export MACHINE_GITHUB_API_TOKEN=${{secrets.MACHINE_GITHUB_API_TOKEN}}
          pub get
          dart tool/release_unreleased_prs.dart